python test_eunaf.py \
    --template EUNAF_EDSRx2_bl \
    --testset_tag BSD100 \
    --N 100 \
    --testset_dir ../../data/BSD100/image_SRF_2/ \
    --train_stage 1 \
    --n_resblocks 16 \
    --n_estimators 4 \
    --scale 2 \
    --eval_tag psnr \
    --visualize