python test_eunaf_by_patches.py \
    --template EUNAF_SRResNetxN \
    --testset_tag Set5RGB \
    --N 100 \
    --testset_dir ../../data/ \
    --train_stage 2 \
    --n_resblocks 16 \
    --n_estimators 4 \
    --scale 4 \
    --eval_tag ssim \
    --rgb_channel \
