python test_eunaf.py \
    --template EUNAF_RCANxN \
    --testset_tag Set14RGB \
    --N 14 \
    --testset_dir ../../data/ \
    --train_stage 2 \
    --n_estimators 4 \
    --scale 3 \
    --eval_tag ssim \
    --weight './checkpoints/EUNAF_RCANx2_x2_nb4_nf64_ng10_st1/_best.t7' \
    # --visualize \